- name: variables and prompt
  hosts: local
  connection: local
  vars_prompt: 
  - name: username
    prompt: what is your name?
    private: false
  - name: password
    prompt: what is your password?
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
       msg: "HELLO, Username is: {{ username }}, password is: {{ password}}"
      