- name: gather gather_facts
  hosts: local
  connection: local
  # ansible collects the info of target server, before it executes any other facts
  tasks:
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"