- name: Install packages
  hosts: local
  connection: local
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
        - nginx
        - mysql
        - zip
